base_dir: ${oc.env:EXPERIMENT_ROOT_DIR}
dataset: "SLAKE"
model_type: "lora"
train_split: "all"
test_split: "all"
mod: "val"
hyperparams_compare:
  rank: [16, 32, 64, 128, 256]
  lr: ["3e-5", "3e-4", "3e-3"]
hyperparams_summarize:
  seed: [123, 124, 125]

output_file_name: "hyperparams_comparison.csv"